Drop useless bumpers
ubi-agni/sr_common pull request #2
Opened 2021-10-01 15:47 UTC by rhaschke

I factored this out from https://github.com/shadow-robot/sr_common/pull/120 to ensure that created files don't change.
- [ ] If really not needed, one should remove the corresponding block instead of commenting it out?
      Alternatively, disable/enable it optionally? @beatrizleon, any thoughts?

2021-10-07 16:18 UTC, beatrizleon commented
@rhaschke Thanks for pointing it out. I have discussed this with the team and we think there is no need to have them so we can remove them instead of commenting them out.

2021-10-10 09:24 UTC, rhaschke commented
I removed the bumper definitions completely now.

2021-10-11 00:57 UTC, beatrizleon requested changes

2021-10-11 00:57 UTC, beatrizleon commented on sr_description/hand/xacro/thumb/thhub.gazebo.xacro
> +      <!-- hub is inside the proximal and not exposed, so bumper is not needed
```suggestion
      <!-- hub is inside the proximal and not exposed, so bumper is not needed  -->
```

2021-10-11 12:03 UTC, beatrizleon approved these changes

2021-12-13 17:47 UTC, closed without merging